o2.notification =
{
	send()
	{
		document.querySelector('.g-alert').classList.add('success');
		document.querySelector('.g-alert__text').classList.add('success__text');
	},
	close()
	{
		document.querySelector('.g-alert').classList.remove('success');
		document.querySelector('.g-alert').classList.remove('error');
		document.querySelector('.g-alert__text').classList.remove('success__text');
		document.querySelector('.g-alert__text').classList.remove('error__text');
	},
	error()
	{
		document.querySelector('.g-alert').classList.add('error');
		document.querySelector('.g-alert__text').classList.add('error__text');
	}
};